Fix saveCanvasState to use correct Excalidraw API methods
- Changed from excalidrawAPI.getScene() (which doesn't exist) to separate calls
- Now using excalidrawAPI.getSceneElements() to get elements
- Now using excalidrawAPI.getAppState() to get app state
- Fixes TypeError: excalidrawAPI.getScene is not a function

The Excalidraw API doesn't have a getScene() method; it provides separate methods for getting elements and app state.